[allowlist]
description = "Allowlist for placeholder values and test configurations"

regexes = [
    '''database-password.*PLACEHOLDER''',
    '''jwt-secret.*PLACEHOLDER''',
    '''redis-password.*PLACEHOLDER''',
    '''POSTGRES_PASSWORD.*postgres''',
    '''ConnectionStrings.*localhost.*postgres'''
]

commits = [
    "db4e3630279d0f149a561f0324b05b4ea116b0f5"
]

paths = [
    "Backend/src/BARQ.API/appsettings.Development.json",
    ".github/workflows/ci-cd-pipeline.yml"
]
