apiVersion: apps/v1
kind: Deployment
metadata:
  name: barq-backend
  namespace: barq-system
  labels:
    app: barq-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: barq-backend
      version: v1
  template:
    metadata:
      labels:
        app: barq-backend
        version: v1
    spec:
      containers:
      - name: barq-backend
        image: ${BACKEND_IMAGE:-barq/backend:latest}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: barq-secrets
              key: database-connection
        - name: JwtSettings__SecretKey
          valueFrom:
            secretKeyRef:
              name: barq-secrets
              key: jwt-secret
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: barq-config
      imagePullSecrets:
      - name: barq-registry-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barq-frontend
  namespace: barq-system
  labels:
    app: barq-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barq-frontend
      version: v1
  template:
    metadata:
      labels:
        app: barq-frontend
        version: v1
    spec:
      containers:
      - name: barq-frontend
        image: ${FRONTEND_IMAGE:-barq/frontend:latest}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: barq-frontend-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barq-database
  namespace: barq-system
  labels:
    app: barq-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barq-database
  template:
    metadata:
      labels:
        app: barq-database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "BarqDB"
        - name: POSTGRES_USER
          value: "barq_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: barq-secrets
              key: database-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: database.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - barq_user
            - -d
            - BarqDB
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - barq_user
            - -d
            - BarqDB
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: barq-database-pvc
      - name: postgres-config
        configMap:
          name: barq-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barq-redis
  namespace: barq-system
  labels:
    app: barq-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barq-redis
  template:
    metadata:
      labels:
        app: barq-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: barq-secrets
              key: redis-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: barq-redis-pvc
