apiVersion: v1
kind: Secret
metadata:
  name: barq-secrets
  namespace: barq-system
type: Opaque
data:
  database-password: ""  # Replace with actual base64 encoded database password
  jwt-secret: ""          # Replace with actual base64 encoded JWT secret
  redis-password: ""      # Replace with actual base64 encoded Redis password
stringData:
  database-connection: "Server=${DATABASE_HOST};Database=${DATABASE_NAME};User Id=${DATABASE_USER};Password=${DATABASE_PASSWORD};TrustServerCertificate=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: barq-tls-secret
  namespace: barq-system
type: kubernetes.io/tls
data:
  tls.crt: ""  # Replace with actual base64 encoded certificate
  tls.key: ""  # Replace with actual base64 encoded private key
