apiVersion: v1
kind: Secret
metadata:
  name: barq-secrets
  namespace: barq-system
type: Opaque
data:
  database-password: "PLACEHOLDER_DATABASE_PASSWORD"
  jwt-secret: "PLACEHOLDER_JWT_SECRET"
  redis-password: "PLACEHOLDER_REDIS_PASSWORD"
stringData:
  database-connection: "Server=PLACEHOLDER_HOST;Database=PLACEHOLDER_DB;User Id=PLACEHOLDER_USER;Password=PLACEHOLDER_PASSWORD;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: barq-tls-secret
  namespace: barq-system
type: kubernetes.io/tls
data:
  tls.crt: "PLACEHOLDER_TLS_CERT"
  tls.key: "PLACEHOLDER_TLS_KEY"
