apiVersion: v1
kind: Secret
metadata:
  name: barq-secrets
  namespace: barq-system
type: Opaque
data:
  database-password: "<base64-encoded-db-password>"
  jwt-secret: "<base64-encoded-jwt-secret>"
  redis-password: "<base64-encoded-redis-password>"
stringData:
  database-connection: "Server=<db-host>;Database=<db-name>;User Id=<db-user>;Password=<db-password>;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: barq-tls-secret
  namespace: barq-system
type: kubernetes.io/tls
data:
  tls.crt: "<base64-encoded-tls-certificate>"
  tls.key: "<base64-encoded-tls-private-key>"
