apiVersion: v1
kind: Secret
metadata:
  name: barq-secrets
  namespace: barq-system
type: Opaque
data:
  database-password: YmFycV9wYXNzd29yZA==  # barq_password
  jwt-secret: eW91ci1zZWNyZXQta2V5LWhlcmU=      # your-secret-key-here
  redis-password: cmVkaXNfcGFzc3dvcmQ=           # redis_password
stringData:
  database-connection: "Server=barq-database;Database=BarqDB;User Id=barq_user;Password=barq_password;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: barq-tls-secret
  namespace: barq-system
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key
